#!/usr/bin/env bash

# Nombre del trabajo
#PBS -N false-friends

# Requerimientos
#PBS -l nodes=1:ppn=64,walltime=00:04:00:00

# Cola de ejecución
#PBS -q quick_jobs

# Directorio de trabajo
#PBS -d /home/sacastro/repos/false-friends

# Correo electrónico
#PBS -M sacastro@fing.edu.uy

# Email
#PBS -m bea

# n: no mail will be sent.
# a: mail is sent when the job is aborted by the batch system.
# b: mail is sent when the job begins execution.
# e: mail is sent when the job terminates.

echo Job Name: $PBS_JOBNAME
echo Working directory: $PBS_O_WORKDIR
echo Queue: $PBS_QUEUE
echo Cantidad de tasks: $PBS_TASKNUM
echo Home: $PBS_O_HOME
echo Puerto del MOM: $PBS_MOMPORT
echo Nombre del usuario: $PBS_O_LOGNAME
echo Idioma: $PBS_O_LANG
echo Cookie: $PBS_JOBCOOKIE
echo Offset de numero de nodos: $PBS_NODENUM
echo Shell: $PBS_O_SHELL
echo JobID: $PBS_O_JOBID
echo Host: $PBS_O_HOST
echo Cola de ejecucion: $PBS_QUEUE
echo Archivo de nodos: $PBS_NODEFILE
echo Path: $PBS_O_PATH
echo
cd $PBS_O_WORKDIR
echo Current path:
pwd
echo
echo Nodos:
cat $PBS_NODEFILE
echo
echo Cantidad de nodos:
NPROCS=$(/usr/bin/wc -l < $PBS_NODEFILE)
echo $NPROCS
echo
echo PPN:
echo $PBS_NUM_PPN
echo

# Ejecuto la tarea
time ./falsefriends.py word_vectors --threads=$PBS_NUM_PPN resources/big/wikipedia_es_preprocesada.txt resources/big/vectors_es.bin
